services:
  dev-db:
    image: postgres:13
    container_name: postgres_container
    environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: my_test_db
    ports:
    - '5432:5432'